import type { AppProps } from 'next/app'
import Head from 'next/head'
import { useEffect, useState } from 'react';

import Layout from '../components/layout'

import { ethConnectionType, useWallet, etherContext } from '../hooks/useeth';
import '../styles/globals.css'

function MyApp({ Component, pageProps }: AppProps) {
  console.log('rendering app')
  const ethConnection: ethConnectionType = useWallet();

  const PageView = () => {
    return (
      <etherContext.Provider value={ethConnection}>
        <Layout>
          <Component {...pageProps} />
        </Layout>
      </etherContext.Provider>
    )
  }

  return (
    <div>
      <Head>
        <title>Pendora</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PageView />
    </div>
  )
}

export default MyApp
